name: Earthly build
on:
  push:
    branches: ['main']
  pull_request:
  schedule:
    - cron: '0 11 * * *'
jobs:
  space-ros:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up earthly
        run: |
          sudo wget https://github.com/earthly/earthly/releases/latest/downloads/earthly-linux-amd64 -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build spaceros image
        run: |
          cd spaceros
          earthly --ci +image
